import '@unocss/reset/tailwind.css'
import 'src/styles/globals.scss'
import '../styles/uno.css'
import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'

import { Inter } from 'next/font/google'

import { TRPCReactProvider } from 'src/trpc/react'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import { theme } from 'src/components/theme/theme'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata = {
  title: '应用名称',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Notifications />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
